// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'GeminiChat-section-header'
  | 'GeminiChat-section-sidenav'
  | 'GeminiChat-sidebar-button';
